enum BankType {
   Bank = "銀行",
   Credit_Union = "信用合作社",
   Farmers = "農會",
   Fisherperson = "漁會",
   Post = "郵局",
}

export const BankData: BankCodeType[] = [
   {
      code: "003",
      cn_name: "交通銀行",
      en_name: "Bank of Communications",
      link: "https://www.bankcomm.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "004",
      cn_name: "台灣銀行",
      en_name: "Bank of Taiwan",
      link: "https://www.bot.com.tw",
      tag: BankType.Bank,
   },
   //excel
   {
      code: "005",
      cn_name: "臺灣土地銀行",
      en_name: "Land Bank of Taiwan",
      link: "https://www.landbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "006",
      cn_name: "合作金庫商業銀行",
      en_name: "Taiwan Cooperative Bank",
      link: "https://www.tcb-bank.com.tw",
      tag: BankType.Bank,
      nickname: ["合庫商銀"],
   },
   {
      code: "007",
      cn_name: "第一商業銀行",
      en_name: "First Bank",
      link: "https://www.firstbank.com.tw",
      tag: BankType.Bank,
      nickname: ["一銀"],
   },
   {
      code: "008",
      cn_name: "華南銀行",
      en_name: "Hua Nan Commercial Bank",
      link: "https://www.hncb.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "009",
      cn_name: "彰化商業銀行",
      en_name: "Chang Hwa Commercial Bank",
      link: "https://www.bankchb.com",
      tag: BankType.Bank,
      nickname: ["彰化銀行"],
   },
   {
      code: "010",
      cn_name: "華僑銀行",
      en_name: "Oversea-Chinese Banking Corporation Limited",
      link: "https://www.ocbc.com/group/gateway",
      tag: BankType.Bank,
   },
   {
      code: "011",
      cn_name: "上海商業儲蓄銀行",
      en_name: "The Shanghai Commercial & Savings Bank",
      link: "https://www.scsb.com.tw",
      tag: BankType.Bank,
      nickname: ["上海銀行", "上海商銀", "上銀"],
   },
   {
      code: "012",
      cn_name: "台北富邦",
      en_name: "Taipei Fubon Bank",
      link: "https://ebank.taipeifubon.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "013",
      cn_name: "國泰世華商業銀行",
      en_name: "Cathay United Bank",
      link: "https://www.cathaybk.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "016",
      cn_name: "高雄銀行",
      en_name: "Bank of Kaohsiung",
      link: "https://www.bok.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "017",
      cn_name: "兆豐國際商業銀行",
      en_name: "Mega International Commercial Bank",
      link: "https://www.megabank.com.tw",
      tag: BankType.Bank,
      nickname: ["兆豐商銀"],
   },
   {
      code: "018",
      cn_name: "全國農業金庫",
      en_name: "Agricultural Bank of Taiwan",
      link: "https://www.agribank.com.tw",
      tag: BankType.Bank,
      nickname: ["農業金庫"],
   },
   {
      code: "021",
      cn_name: "花旗銀行",
      en_name: "Citibank Taiwan",
      link: "https://www.citibank.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "025",
      cn_name: "菲商菲律賓首都銀行",
      en_name: "Metropolitan Bank & Trust Company",
      link: "http://www.metrobank.com.tw",
      tag: BankType.Bank,
      nickname: ["首都銀行"],
   },
   {
      code: "039",
      cn_name: "澳商澳盛銀行集團股份有限公司",
      en_name: "Australia & New Zealand Banking Group Limited",
      link: "https://www.anz.com/institutional/global/taiwan/zh-hant/",
      tag: BankType.Bank,
   },
   {
      code: "040",
      cn_name: "中華開發金控",
      en_name: "China Development Industrial Bank",
      link: "https://www.cdfholding.com/",
      tag: BankType.Bank,
   },
   {
      code: "050",
      cn_name: "臺灣中小企業銀行",
      en_name: "Taiwan Business Bank",
      link: "https://www.tbb.com.tw/",
      tag: BankType.Bank,
      nickname: ["臺灣企銀"],
   },
   {
      code: "053",
      cn_name: "台中商業銀行",
      en_name: "Taichung Commercial Bank",
      link: "https://www.tcbbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "054",
      cn_name: "京城商業銀行",
      en_name: "King's Town Bank",
      link: "https://customer.ktb.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "075",
      cn_name: "東亞銀行",
      en_name: "The Bank of East Asia",
      link: "https://www.hkbea.com/html/tc/",
      tag: BankType.Bank,
   },
   {
      code: "081",
      cn_name: "滙豐商業銀行",
      en_name: "Hongkong Bank",
      link: "https://www.hsbc.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "083",
      cn_name: "渣打銀行",
      en_name: "Standard Chartered",
      link: "https://www.sc.com/tw/",
      tag: BankType.Bank,
   },
   {
      code: "101",
      cn_name: "瑞興商業銀行",
      en_name: "Taipei Star Bank",
      link: "https://www.taipeistarbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "102",
      cn_name: "華泰銀行",
      en_name: "Hwatai Bank",
      link: "https://www.hwataibank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "103",
      cn_name: "新光銀行",
      en_name: "Shin Kong Bank",
      link: "https://www.skbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "104",
      cn_name: "台北市第五信用合作社",
      en_name: "The Fifth Credit Cooperation of Taipei",
      link: "https://taipei-tfcc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "108",
      cn_name: "陽信商業銀行",
      en_name: "Sunny Bank",
      link: "https://www.sunnybank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "114",
      cn_name: "基隆第一信用合作社",
      en_name: "Keelung First Credit Cooperative",
      link: "https://www.kfcc.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "115",
      cn_name: "基隆二信",
      en_name: "The Second Credit Cooperative Of Keelung",
      link: "https://www.kscc.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "118",
      cn_name: "板信商業銀行",
      en_name: "Bank of Panhsin",
      link: "https://www.bop.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "119",
      cn_name: "淡水第一信用合作社",
      en_name: "Tamshui First Credit Bank",
      link: "https://www.tfccbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "120",
      cn_name: "新北市淡水信用合作社",
      en_name: "The Tamsui Credit Cooperative",
      link: "https://tsc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "124",
      cn_name: "宜蘭信用合作社",
      en_name: "The Credit Cooperative of Yi-Lan",
      link: "https://ilan.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "127",
      cn_name: "桃園信用合作社",
      en_name: "The Credit Co-operative of Taoyuan",
      link: "https://tycbank.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "130",
      cn_name: "新竹第一信用合作社",
      en_name: "The First Credit Cooperative of Hsin-chu",
      link: "https://www.hcfcbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "132",
      cn_name: "新竹第三信用合作社",
      en_name: "The Third Credit Cooperative of Hsinchu",
      link: "https://www.hc3cbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "146",
      cn_name: "台中市第二信用合作社",
      en_name: "The Second credit cooperative of TXG",
      link: "https://www.tsca.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "147",
      cn_name: "三信商業銀行",
      en_name: "COTA Commercial Bank",
      link: "https://www.cotabank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "158",
      cn_name: "彰化第一信用合作社",
      en_name: "The First Credit Cooperative of Changhua",
      link: "https://chfc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "161",
      cn_name: "彰化第五信用合作社",
      en_name: "The Fifth Credit Cooperative Of Changhua",
      link: "https://fs161.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "162",
      cn_name: "彰化第六信用合作社",
      en_name: "The Sixth Credit Cooperative Of Changhua",
      link: "https://www.ch6c.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "163",
      cn_name: "彰化第十信用合作社",
      en_name: "The Tenth Credit Cooperative of Changhua",
      link: "https://ch10c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "165",
      cn_name: "彰化縣鹿港信用合作社",
      en_name: "The Credit Cooperative of Lu Kang",
      link: "https://lkbank.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "178",
      cn_name: "嘉義市第三信用合作社",
      en_name: "The Third Credit Cooperative of Chiayi",
      link: "https://chiayi3c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "188",
      cn_name: "台南三信",
      en_name: "Tainan Third Credit Cooperative",
      link: "https://ttc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "204",
      cn_name: "高雄市第三信用合作社",
      en_name: "The Kaohsiung Third Credit Cooperative",
      link: "https://www.kh3c.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "215",
      cn_name: "花蓮第一信用合作社",
      en_name: "The First Credit Cooperative of Hualien",
      link: "https://www.hua215.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "216",
      cn_name: "花蓮第二信用合作社",
      en_name: "Hualien 2nd Credit Cooperative",
      link: "https://www.hl2c.com.tw/hl2c/",
      tag: BankType.Credit_Union,
   },
   {
      code: "222",
      cn_name: "澎湖縣第一信用合作社",
      en_name: "Penghu First Credit Cooperative Assn",
      link: "https://pfcco.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "223",
      cn_name: "澎湖第二信用合作社",
      en_name: "Penghu 2nd Credit Society",
      link: "https://ph2c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "224",
      cn_name: "金門縣信用合作社",
      en_name: "Kinmen credit cooperative",
      link: "https://kinmen.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   { code: "512", cn_name: "雲林漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "515", cn_name: "嘉義漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "517", cn_name: "南市區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "518", cn_name: "南縣漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "彌陀漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "永安漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "興達港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "林園區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "東港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "琉球區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "林邊區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "524", cn_name: "新港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "525", cn_name: "澎湖區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "605", cn_name: "高雄市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "613", cn_name: "名間農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "永靖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "秀水農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "二林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "埔心農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "員林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "埤頭鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "竹塘農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "四湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "大埤農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "二崙農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "口湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "莿桐農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "褒忠農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "斗六農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "西螺農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "虎尾農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "崙背鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "台西農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "古坑農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "斗南農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "六腳農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "朴子農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "太保農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "鹿草農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "大埔農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "水上鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "民雄農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "溪口農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "竹崎農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "布袋鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "東石農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "新港農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "大林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "梅山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "嘉義農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "番路農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "義竹農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "歸仁農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "六甲農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "善化鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "西港農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "北門農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "佳里鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "永康農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "鹽水農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "新營農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "將軍農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "玉井農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "鳳山市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "阿蓮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "仁武農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "大社農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "田寮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "鳥松農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "梓官農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "林園農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "大寮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "橋頭農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "燕巢農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "永安農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "湖內農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "路竹農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "彌陀農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "甲仙農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "杉林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "旗山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "岡山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "茄萣農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "美濃農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "恒春農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "滿州農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "新埤農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "枋山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "東港鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "里港鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "南州農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "崁頂鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "麟洛農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "琉球農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "九如鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "富里鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "壽豐農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "吉安農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "新秀農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "太麻里農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "東河農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "台東農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "成功農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "關山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "池上農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "鹿野農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "長濱農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "624", cn_name: "澎湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "625", cn_name: "台中市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "627", cn_name: "連江縣農會", en_name: "", link: undefined, tag: BankType.Farmers },
   {
      code: "700",
      cn_name: "中華郵政",
      en_name: "Chunghwa Post",
      link: "https://www.post.gov.tw/post/internet/index.jsp",
      tag: BankType.Post,
   },
   {
      code: "803",
      cn_name: "聯邦商業銀行",
      en_name: "Union Bank of Taiwan",
      link: "https://www.ubot.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "805",
      cn_name: "遠東國際商業銀行",
      en_name: "Far Eastern International Bank",
      link: "https://www.feib.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "806",
      cn_name: "元大商業銀行",
      en_name: "Yuanta Commercial Bank",
      link: "https://www.yuantabank.com.tw/bank/",
      tag: BankType.Bank,
   },
   {
      code: "808",
      cn_name: "玉山商業銀行",
      en_name: "E.SUN Commercial Bank",
      link: "https://www.esunbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "809",
      cn_name: "凱基商業銀行",
      en_name: "KGI Bank.",
      link: "https://www.kgibank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "812",
      cn_name: "台新國際商業銀行",
      en_name: "Taishin International Bank",
      link: "https://www.taishinbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "815",
      cn_name: "日盛國際商業銀行",
      en_name: "JihSun International Commercial Bank",
      link: "https://www.jihsunbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "816",
      cn_name: "安泰商業銀行",
      en_name: "Entie Commercial Bank",
      link: "https://www.entiebank.com.tw/entie/home",
      tag: BankType.Bank,
   },
   {
      code: "822",
      cn_name: "中國信託商業銀行",
      en_name: "CTBC Bank",
      link: "https://www.ctbcbank.com/",
      tag: BankType.Bank,
   },
   {
      code: "823",
      cn_name: "將來銀行",
      en_name: "Next Bank",
      link: "https://www.nextbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "824",
      cn_name: "連線商業銀行",
      en_name: "LINE Bank",
      link: "https://www.linebank.com.tw/",
      tag: BankType.Bank,
   },
];
