enum BankType {
   Bank = "銀行",
   Credit_Union = "信用合作社",
   Farmers = "農會",
   Fisherperson = "漁會",
   Post = "郵局",
   Pay = "行動支付",
}

export const BankData: BankCodeType[] = [
   {
      code: "003",
      cn_name: "交通銀行",
      en_name: "Bank of Communications",
      link: "https://www.bankcomm.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "004",
      cn_name: "台灣銀行",
      en_name: "Bank of Taiwan",
      link: "https://www.bot.com.tw",
      tag: BankType.Bank,
   },
   //excel
   {
      code: "005",
      cn_name: "臺灣土地銀行",
      en_name: "Land Bank of Taiwan",
      link: "https://www.landbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "006",
      cn_name: "合作金庫商業銀行",
      en_name: "Taiwan Cooperative Bank",
      link: "https://www.tcb-bank.com.tw",
      tag: BankType.Bank,
      nickname: ["合庫商銀"],
   },
   {
      code: "007",
      cn_name: "第一商業銀行",
      en_name: "First Bank",
      link: "https://www.firstbank.com.tw",
      tag: BankType.Bank,
      nickname: ["一銀"],
   },
   {
      code: "008",
      cn_name: "華南銀行",
      en_name: "Hua Nan Commercial Bank",
      link: "https://www.hncb.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "009",
      cn_name: "彰化商業銀行",
      en_name: "Chang Hwa Commercial Bank",
      link: "https://www.bankchb.com",
      tag: BankType.Bank,
      nickname: ["彰化銀行"],
   },
   {
      code: "010",
      cn_name: "華僑銀行",
      en_name: "Oversea-Chinese Banking Corporation Limited",
      link: "https://www.ocbc.com/group/gateway",
      tag: BankType.Bank,
   },
   {
      code: "011",
      cn_name: "上海商業儲蓄銀行",
      en_name: "The Shanghai Commercial & Savings Bank",
      link: "https://www.scsb.com.tw",
      tag: BankType.Bank,
      nickname: ["上海銀行", "上海商銀", "上銀"],
   },
   {
      code: "012",
      cn_name: "台北富邦",
      en_name: "Taipei Fubon Bank",
      link: "https://ebank.taipeifubon.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "013",
      cn_name: "國泰世華商業銀行",
      en_name: "Cathay United Bank",
      link: "https://www.cathaybk.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "016",
      cn_name: "高雄銀行",
      en_name: "Bank of Kaohsiung",
      link: "https://www.bok.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "017",
      cn_name: "兆豐國際商業銀行",
      en_name: "Mega International Commercial Bank",
      link: "https://www.megabank.com.tw",
      tag: BankType.Bank,
      nickname: ["兆豐商銀"],
   },
   {
      code: "018",
      cn_name: "全國農業金庫",
      en_name: "Agricultural Bank of Taiwan",
      link: "https://www.agribank.com.tw",
      tag: BankType.Bank,
      nickname: ["農業金庫"],
   },
   {
      code: "021",
      cn_name: "花旗銀行",
      en_name: "Citibank Taiwan",
      link: "https://www.citibank.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "025",
      cn_name: "菲商菲律賓首都銀行",
      en_name: "Metropolitan Bank & Trust Company",
      link: "http://www.metrobank.com.tw",
      tag: BankType.Bank,
      nickname: ["首都銀行"],
   },
   {
      code: "039",
      cn_name: "澳商澳盛銀行集團股份有限公司",
      en_name: "Australia & New Zealand Banking Group Limited",
      link: "https://www.anz.com/institutional/global/taiwan/zh-hant/",
      tag: BankType.Bank,
   },
   {
      code: "040",
      cn_name: "中華開發金控",
      en_name: "China Development Industrial Bank",
      link: "https://www.cdfholding.com/",
      tag: BankType.Bank,
   },
   {
      code: "050",
      cn_name: "臺灣中小企業銀行",
      en_name: "Taiwan Business Bank",
      link: "https://www.tbb.com.tw/",
      tag: BankType.Bank,
      nickname: ["臺灣企銀"],
   },
   {
      code: "052",
      cn_name: "渣打銀行",
      en_name: "Standard Chartered",
      link: "https://www.sc.com/tw/",
      tag: BankType.Bank,
   },
   {
      code: "053",
      cn_name: "台中商業銀行",
      en_name: "Taichung Commercial Bank",
      link: "https://www.tcbbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "054",
      cn_name: "京城商業銀行",
      en_name: "King's Town Bank",
      link: "https://customer.ktb.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "075",
      cn_name: "東亞銀行",
      en_name: "The Bank of East Asia",
      link: "https://www.hkbea.com/html/tc/",
      tag: BankType.Bank,
   },
   {
      code: "081",
      cn_name: "滙豐商業銀行",
      en_name: "Hongkong Bank",
      link: "https://www.hsbc.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "101",
      cn_name: "瑞興商業銀行",
      en_name: "Taipei Star Bank",
      link: "https://www.taipeistarbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "102",
      cn_name: "華泰銀行",
      en_name: "Hwatai Bank",
      link: "https://www.hwataibank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "103",
      cn_name: "新光銀行",
      en_name: "Shin Kong Bank",
      link: "https://www.skbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "104",
      cn_name: "台北市第五信用合作社",
      en_name: "The Fifth Credit Cooperation of Taipei",
      link: "https://taipei-tfcc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "108",
      cn_name: "陽信商業銀行",
      en_name: "Sunny Bank",
      link: "https://www.sunnybank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "114",
      cn_name: "基隆第一信用合作社",
      en_name: "Keelung First Credit Cooperative",
      link: "https://www.kfcc.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "115",
      cn_name: "基隆二信",
      en_name: "The Second Credit Cooperative Of Keelung",
      link: "https://www.kscc.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "118",
      cn_name: "板信商業銀行",
      en_name: "Bank of Panhsin",
      link: "https://www.bop.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "119",
      cn_name: "淡水第一信用合作社",
      en_name: "Tamshui First Credit Bank",
      link: "https://www.tfccbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "120",
      cn_name: "新北市淡水信用合作社",
      en_name: "The Tamsui Credit Cooperative",
      link: "https://tsc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "124",
      cn_name: "宜蘭信用合作社",
      en_name: "The Credit Cooperative of Yi-Lan",
      link: "https://ilan.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "127",
      cn_name: "桃園信用合作社",
      en_name: "The Credit Co-operative of Taoyuan",
      link: "https://tycbank.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "130",
      cn_name: "新竹第一信用合作社",
      en_name: "The First Credit Cooperative of Hsin-chu",
      link: "https://www.hcfcbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "132",
      cn_name: "新竹第三信用合作社",
      en_name: "The Third Credit Cooperative of Hsinchu",
      link: "https://www.hc3cbank.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "146",
      cn_name: "台中市第二信用合作社",
      en_name: "The Second credit cooperative of TXG",
      link: "https://www.tsca.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "147",
      cn_name: "三信商業銀行",
      en_name: "COTA Commercial Bank",
      link: "https://www.cotabank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "158",
      cn_name: "彰化第一信用合作社",
      en_name: "The First Credit Cooperative of Changhua",
      link: "https://chfc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "161",
      cn_name: "彰化第五信用合作社",
      en_name: "The Fifth Credit Cooperative Of Changhua",
      link: "https://fs161.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "162",
      cn_name: "彰化第六信用合作社",
      en_name: "The Sixth Credit Cooperative Of Changhua",
      link: "https://www.ch6c.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "163",
      cn_name: "彰化第十信用合作社",
      en_name: "The Tenth Credit Cooperative of Changhua",
      link: "https://ch10c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "165",
      cn_name: "彰化縣鹿港信用合作社",
      en_name: "The Credit Cooperative of Lu Kang",
      link: "https://lkbank.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "178",
      cn_name: "嘉義市第三信用合作社",
      en_name: "The Third Credit Cooperative of Chiayi",
      link: "https://chiayi3c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "188",
      cn_name: "台南三信",
      en_name: "Tainan Third Credit Cooperative",
      link: "https://ttc.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "204",
      cn_name: "高雄市第三信用合作社",
      en_name: "The Kaohsiung Third Credit Cooperative",
      link: "https://www.kh3c.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "215",
      cn_name: "花蓮第一信用合作社",
      en_name: "The First Credit Cooperative of Hualien",
      link: "https://www.hua215.com.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "216",
      cn_name: "花蓮第二信用合作社",
      en_name: "Hualien 2nd Credit Cooperative",
      link: "https://www.hl2c.com.tw/hl2c/",
      tag: BankType.Credit_Union,
   },
   {
      code: "222",
      cn_name: "澎湖縣第一信用合作社",
      en_name: "Penghu First Credit Cooperative Assn",
      link: "https://pfcco.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "223",
      cn_name: "澎湖第二信用合作社",
      en_name: "Penghu 2nd Credit Society",
      link: "https://ph2c.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "224",
      cn_name: "金門縣信用合作社",
      en_name: "Kinmen credit cooperative",
      link: "https://kinmen.scu.org.tw/",
      tag: BankType.Credit_Union,
   },
   {
      code: "512",
      cn_name: "雲林區漁會",
      en_name: "Yunlin Fisherman's Association",
      link: "http://www.ylfish.com.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "515",
      cn_name: "嘉義區漁會",
      en_name: "Chiayi Fisherman's Association",
      link: "http://www.cyfae.org.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "517",
      cn_name: "南市區漁會",
      link: "https://www.fast.org.tw/d50/index.html",
      tag: BankType.Fisherperson,
   },
   {
      code: "518",
      cn_name: "南縣區漁會",
      link: "https://nanxianfa.com/",
      tag: BankType.Fisherperson,
   },
   {
      code: "521",
      cn_name: "高雄市彌陀區漁會",
      link: "http://www.mituo2011.com/",
      tag: BankType.Fisherperson,
   },
   {
      code: "521",
      cn_name: "永安區漁會",
      en_name: "Yung An Fisherman's Association",
      link: "http://www.yafa.org.tw/",
      tag: BankType.Fisherperson,
   },
   { code: "521", cn_name: "興達港區漁會", tag: BankType.Fisherperson },
   {
      code: "521",
      cn_name: "林園區漁會",
      link: "http://www.naffic.org.tw/default2.aspx?EpfJdId9UuAsXUMmgmlARNMWj4N6%2FX9m",
      tag: BankType.Fisherperson,
   },
   {
      code: "523",
      cn_name: "東港區漁會",
      link: "http://www.tkfisher.org.tw/default2.aspx?EpfJdId9UuCM43XlWesODXH2pjBjmdrr",
      tag: BankType.Fisherperson,
   },
   {
      code: "523",
      cn_name: "琉球區漁會",
      en_name: "Liu-chiu Fisher Men's Association",
      link: "http://www.liuchiu.org.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "523",
      cn_name: "林邊區漁會",
      link: "http://www.linfish.org.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "524",
      cn_name: "新港區漁會",
      link: "https://kuroshiofish.org.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "525",
      cn_name: "澎湖區漁會",
      link: "https://penghu-fisher.org.tw/",
      tag: BankType.Fisherperson,
   },
   {
      code: "605",
      cn_name: "高雄市農會",
      en_name: "Kaohsiung City Farmers",
      link: "http://www.kcfa.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "613",
      cn_name: "名間鄉農會",
      link: "http://www.miji.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "永靖鄉農會",
      link: "http://www.yjfarmer.org.tw/default2.aspx?EpfJdId9UuCJctf5vXgyGjTtWy1gfOX9",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "秀水鄉農會",
      link: "http://www.hsfarm.org.tw/default2.aspx?EpfJdId9UuDNTO91R3HUNleLPygPwIYO",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "二林鎮農會",
      en_name: "Erlin Farmers Association",
      link: "http://www.rlfa.org.tw/Default.aspx",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "埔心鄉農會",
      en_name: "Changhua County Pushin Township Farmers Association",
      link: "http://pushinfa.linker.tw/front/index.php",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "員林市農會",
      en_name: "Changhua County Yuanlin Farmers Association",
      link: "http://www.yuanlinfa.com.tw/front/index.php",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "埤頭鄉農會",
      link: "http://www.pitou.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   {
      code: "614",
      cn_name: "竹塘鄉農會",
      en_name: "Changhua County Jhutang Farmers Association",
      link: "http://www.chu.org.tw/front/index.php",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "四湖鄉農會",
      en_name: "Sihu Farmers Association",
      link: "http://www.sihu.org.tw/default.asp",
      tag: BankType.Farmers,
   },
   { code: "616", cn_name: "大埤鄉農會", tag: BankType.Farmers },
   {
      code: "616",
      cn_name: "二崙鄉農會",
      en_name: "Yunlin County Erlun Farmers Association",
      link: "http://www.erlun.org.tw/index01.html",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "口湖鄉農會",
      en_name: "Kou-hu Farmers Association",
      link: "https://www.fast.org.tw/p19/",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "莿桐鄉農會",
      link: "http://www.ctgo.org.tw/index.html",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "褒忠鄉農會",
      en_name: "Baojhong Farmers Association",
      link: "http://www.naffic.org.tw/default2.aspx?EpfJdId9UuAsXUMmgmlARHG6TAHWwkQV",
      tag: BankType.Farmers,
   },
   { code: "616", cn_name: "斗六市農會", tag: BankType.Farmers },
   { code: "616", cn_name: "西螺鎮農會", link: "http://www.slofa.org/", tag: BankType.Farmers },
   {
      code: "616",
      cn_name: "虎尾鎮農會",
      link: "http://www.hwfa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "崙背鄉農會",
      en_name: "Lunpei Farmers Association",
      link: "http://lunpeifa.naffic.org.tw/default2.aspx?EpfJdId9UuCM43XlWesODU8ja%2fLxFP0g",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "台西鄉農會",
      en_name: "TaiShi Farmers Association",
      link: "http://taishi.naffic.org.tw/default2.aspx?EpfJdId9UuCM43XlWesODYvt%2fmK42fVS",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "古坑鄉農會",
      link: "http://www.gkcafe.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "616",
      cn_name: "斗南鎮農會",
      en_name: "DouNan Town Farmers Association",
      link: "http://www.dnrice.org/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "六腳鄉農會",
      en_name: "Lioujiau Farmers Association",
      link: "https://www.fast.org.tw/q15/",
      tag: BankType.Farmers,
   },
   { code: "617", cn_name: "朴子市農會", link: "http://www.polon.org.tw/", tag: BankType.Farmers },
   {
      code: "617",
      cn_name: "太保市農會",
      en_name: "Tai-po City Farmers Association",
      link: "http://www.taipo.org.tw/index.asp",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "鹿草鄉農會",
      en_name: "Lucao Farmers Association",
      link: "http://www.lufa.org.tw/default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "水上鄉農會",
      en_name: "Shueishang Farmers Association",
      link: "http://www.waterfa.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "民雄鄉農會",
      en_name: "Minsyong Township Farmers Association",
      link: "http://www.minsyong.org.tw/index.asp",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "溪口鄉農會",
      link: "http://www.xikou.org.tw/main.aspx",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "竹崎地區農會",
      en_name: "Zuchi Farmers Association",
      link: "http://www.zuchifarm.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "布袋鎮農會",
      link: "http://www.bdfa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   { code: "617", cn_name: "東石鄉農會", tag: BankType.Farmers },
   {
      code: "617",
      cn_name: "新港鄉農會",
      en_name: "Xingang Farmers Association",
      link: "https://www.singang.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "大林鎮農會",
      link: "http://dalin.naffic.org.tw/default2.aspx?EpfJdId9UuA2OTk3x3xRf3obB0%2bBcm3j",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "梅山農會",
      en_name: "Meishan Farmers Association",
      link: "http://www.msfa.com.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "嘉義縣農會",
      link: "http://www.cyfa.org.tw/show.asp",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "番路鄉農會",
      en_name: "Fanlu Farmers Association",
      link: "http://www.fanlu.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "617",
      cn_name: "義竹鄉農會",
      link: "http://www.yijhu.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   { code: "618", cn_name: "歸仁區農會", tag: BankType.Farmers },
   { code: "618", cn_name: "六甲區農會", tag: BankType.Farmers },
   {
      code: "618",
      cn_name: "善化區農會",
      en_name: "Shanhua District Farmers Association",
      link: "http://www.sh-fa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "西港區農會",
      link: "http://www.sgfa.org.tw/index.asp",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "北門區農會",
      link: "http://www.beimen.org.tw/index.asp#",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "佳里區農會",
      link: "http://www.jlfa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "永康區農會",
      en_name: "Yong Kang District Farmers Association",
      link: "http://www.farm.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "鹽水區農會",
      en_name: "Yanshuei Farmers Association",
      link: "http://www.yesfarm.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "新營區農會",
      link: "http://www.sinying.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "將軍區農會",
      en_name: "Jiang Hiun Township Farmers Association",
      link: "http://www.jiangjun.com.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "618",
      cn_name: "玉井區農會",
      en_name: "Yu-Ching District Farmers Association",
      link: "http://www.ycfa.org.tw",
      tag: BankType.Farmers,
   },
   { code: "619", cn_name: "鳳山區農會", link: "http://www.fsfa.org.tw/", tag: BankType.Farmers },
   {
      code: "619",
      cn_name: "阿蓮區農會",
      en_name: "Alian District Farmers Association",
      link: "http://www.alfa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "仁武區農會",
      en_name: "Renwn Farmers Association",
      link: "http://www.rwfa.org.tw/Default.htm",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "大社區農會",
      en_name: "Dashe Area Farmers Association",
      link: "http://www.dashe.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "田寮區農會",
      en_name: "Tianlion District Farmers Association",
      link: "https://www.fast.org.tw/s07/",
      tag: BankType.Farmers,
   },
   { code: "619", cn_name: "鳥松區農會", tag: BankType.Farmers },
   {
      code: "619",
      cn_name: "梓官區農會",
      en_name: "Tzukuan Farmers Association",
      link: "http://www.zgfa.org.tw/Default.htm",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "林園區農會",
      link: "https://www.fast.org.tw/s20/",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "大寮區農會",
      en_name: "Daliao District Farmers Association",
      link: "https://www.dlfa.com.tw/",
      tag: BankType.Farmers,
   },
   { code: "619", cn_name: "橋頭區農會", tag: BankType.Farmers },
   {
      code: "619",
      cn_name: "燕巢區農會",
      en_name: "Yanchao District Farmers Association",
      link: "http://www.yenfa.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "永安區農會",
      en_name: "Yong Kang District Farmers Association",
      link: "https://oscar.fast.org.tw/",
      tag: BankType.Farmers,
   },
   { code: "619", cn_name: "湖內區農會", link: "http://www.hunei.org.tw/", tag: BankType.Farmers },
   { code: "619", cn_name: "路竹區農會", tag: BankType.Farmers },
   { code: "619", cn_name: "彌陀區農會", link: "http://www.mituo2011.com/", tag: BankType.Farmers },
   {
      code: "619",
      cn_name: "甲仙地區農會",
      link: "http://www.jxfa.org.tw/index.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "杉林區農會",
      link: "http://www.sl-fa.org.tw/Default.aspx",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "旗山區農會",
      link: "http://www.chisun.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "岡山區農會",
      en_name: "Ganshan District Farmers Association",
      link: "http://www.gsfa.org.tw/default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "茄萣區農會",
      en_name: "Qieding District Farmers Association",
      link: "http://www.ks-cdfa.org.tw/default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "619",
      cn_name: "美濃區農會",
      en_name: "Meinong Farmers Association",
      link: "https://www.meinong.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "恆春鎮農會",
      link: "https://www.hcfarm.org.tw/",
      tag: BankType.Farmers,
   },
   { code: "620", cn_name: "滿州鄉農會", link: "https://manzhou.com.tw/", tag: BankType.Farmers },
   { code: "620", cn_name: "新埤鄉農會", tag: BankType.Farmers },
   {
      code: "620",
      cn_name: "枋山地區農會",
      en_name: "Ping Dong Fang Shan Area Farmers Association",
      link: "https://www.mango.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "東港鎮農會",
      en_name: "Donggang Farmers Association",
      link: "https://www.dgpa.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "里港鄉農會",
      link: "http://www.lgfa.org.tw/index.htm",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "南州地區農會",
      en_name: "Nanzhou District Farmers Association",
      link: "https://ptnzfa.com.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "崁頂鄉農會",
      link: "http://www.ktfa.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "麟洛鄉農會",
      link: "https://www.fast.org.tw/t10/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "琉球鄉農會",
      link: "https://www.fast.org.tw/t21/",
      tag: BankType.Farmers,
   },
   {
      code: "620",
      cn_name: "九如鄉農會",
      en_name: "Jiuru Township Farmers Association",
      link: "http://www.jiuru.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "621",
      cn_name: "富里鄉農會",
      en_name: "Hsien Farmers Association",
      link: "http://www.fulifa.org.tw/Default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "621",
      cn_name: "壽豐鄉農會",
      en_name: "Shoufong Farmers Association",
      link: "https://www.shoufong.org/",
      tag: BankType.Farmers,
   },
   {
      code: "621",
      cn_name: "吉安鄉農會",
      link: "http://www.ji-an.org.tw/main.asp",
      tag: BankType.Farmers,
   },
   { code: "621", cn_name: "新秀地區農會", tag: BankType.Farmers },
   {
      code: "622",
      cn_name: "太麻里地區農會",
      en_name: "Taimali Farmers Association",
      link: "https://www.taimalifarmer.com.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "東河鄉農會",
      en_name: "Donghe Farmers Association",
      link: "http://www.dhfa.org.tw/Default.htm",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "臺東縣農會",
      en_name: "Taitung County Farmers Association",
      link: "https://www.toyugimall.com.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "成功鎮農會",
      en_name: "Cheng Gong Township Farmers Association",
      link: "http://www.cgtfa.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "關山鎮農會",
      link: "http://www.ksfa.org.tw/default.asp",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "池上鄉農會",
      en_name: "Chi-shang Farmers Association",
      link: "https://www.csfa.com.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "622",
      cn_name: "鹿野地區農會",
      link: "http://www.luyeah.com.tw/default.asp",
      tag: BankType.Farmers,
   },
   { code: "622", cn_name: "長濱鄉農會", tag: BankType.Farmers },
   {
      code: "624",
      cn_name: "澎湖縣農會",
      link: "https://www.phfafresh.org.tw/",
      tag: BankType.Farmers,
   },
   {
      code: "625",
      cn_name: "台中市農會",
      en_name: "Taichung Farmers Association",
      link: "https://www.tcfarmers.org.tw/",
      tag: BankType.Farmers,
   },
   { code: "627", cn_name: "連江縣農會", tag: BankType.Farmers },
   {
      code: "700",
      cn_name: "中華郵政",
      en_name: "Chunghwa Post",
      link: "https://www.post.gov.tw/post/internet/index.jsp",
      tag: BankType.Post,
   },
   {
      code: "803",
      cn_name: "聯邦商業銀行",
      en_name: "Union Bank of Taiwan",
      link: "https://www.ubot.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "805",
      cn_name: "遠東國際商業銀行",
      en_name: "Far Eastern International Bank",
      link: "https://www.feib.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "806",
      cn_name: "元大商業銀行",
      en_name: "Yuanta Commercial Bank",
      link: "https://www.yuantabank.com.tw/bank/",
      tag: BankType.Bank,
   },
   {
      code: "807",
      cn_name: "永豐商業銀行",
      en_name: "Bank SinoPac",
      link: "https://bank.sinopac.com/",
      tag: BankType.Bank,
   },
   {
      code: "808",
      cn_name: "玉山商業銀行",
      en_name: "E.SUN Commercial Bank",
      link: "https://www.esunbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "809",
      cn_name: "凱基商業銀行",
      en_name: "KGI Bank",
      link: "https://www.kgibank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "810",
      cn_name: "星展銀行",
      en_name: "DBS Bank",
      link: "https://www.dbs.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "812",
      cn_name: "台新國際商業銀行",
      en_name: "Taishin International Bank",
      link: "https://www.taishinbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "815",
      cn_name: "日盛國際商業銀行",
      en_name: "JihSun International Commercial Bank",
      link: "https://www.jihsunbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "816",
      cn_name: "安泰商業銀行",
      en_name: "Entie Commercial Bank",
      link: "https://www.entiebank.com.tw/entie/home",
      tag: BankType.Bank,
   },
   {
      code: "822",
      cn_name: "中國信託商業銀行",
      en_name: "CTBC Bank",
      link: "https://www.ctbcbank.com/",
      tag: BankType.Bank,
   },
   {
      code: "823",
      cn_name: "將來銀行",
      en_name: "Next Bank",
      link: "https://www.nextbank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "824",
      cn_name: "連線商業銀行",
      en_name: "LINE Bank",
      link: "https://www.linebank.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "826",
      cn_name: "樂天國際商業銀行",
      en_name: "Rakuten Bank",
      link: "https://www.rakuten-bank.com.tw",
      tag: BankType.Bank,
   },
   {
      code: "048",
      cn_name: "王道商業銀行",
      en_name: "O-Bank",
      link: "https://www.o-bank.com/",
      tag: BankType.Bank,
   },
   {
      code: "390",
      cn_name: "悠遊付",
      en_name: "Easy Wallet",
      link: "https://easywallet.easycard.com.tw/",
      tag: BankType.Pay,
   },
   {
      code: "391",
      cn_name: "一卡通",
      en_name: "iPASS",
      link: "https://www.i-pass.com.tw/",
      tag: BankType.Pay,
   },
   {
      code: "392",
      cn_name: "愛金卡",
      en_name: "icash pay",
      link: "https://www.icash.com.tw",
      tag: BankType.Pay,
   },

   {
      code: "394",
      cn_name: "Pi拍錢包",
      en_name: "Pi Mobile Technology Inc",
      link: "https://www.piapp.com.tw/",
      tag: BankType.Pay,
   },
   {
      code: "395",
      cn_name: "橘子支付",
      en_name: "Gama Pay",
      link: "https://www.gamapay.com.tw/",
      tag: BankType.Pay,
   },
   {
      code: "396",
      cn_name: "街口支付",
      en_name: "JKOS Network Co",
      link: "https://www.jkos.com/",
      tag: BankType.Pay,
   },
   {
      code: "397",
      cn_name: "歐付寶電子支付",
      en_name: "O'Pay Electronic Payment Co",
      link: "https://www.opay.tw/Landing",
      tag: BankType.Pay,
   },
   {
      code: "398",
      cn_name: "ezPay簡單付",
      en_name: "ezPay Co",
      link: "https://www.ezpay.com.tw/",
      tag: BankType.Pay,
   },
];
