enum BankType {
   Bank = "銀行",
   Credit_Union = "信用合作社",
   Farmers = "農會",
   Fisherperson = "漁會",
   Post = "郵局",
}

export const BankData: BankCodeType[] = [
   {
      code: "003",
      cn_name: "交通銀行",
      en_name: "Bank of Communications",
      link: "https://www.bankcomm.com.tw/",
      tag: BankType.Bank,
   },
   {
      code: "004",
      cn_name: "台灣銀行",
      en_name: "Bank of Taiwan",
      link: "https://www.bot.com.tw",
      tag: BankType.Bank,
   },
   //excel
   { code: "001", cn_name: "中央信託", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "003", cn_name: "交通銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "004", cn_name: "台灣銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "005", cn_name: "土地銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "006", cn_name: "合庫商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "007", cn_name: "第一銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "008", cn_name: "華南銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "009", cn_name: "彰化銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "010", cn_name: "華僑銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "011", cn_name: "上海銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "012", cn_name: "台北富邦", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "013", cn_name: "國泰世華", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "016", cn_name: "高雄銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "017", cn_name: "兆豐商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "018", cn_name: "農業金庫", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "021", cn_name: "花旗銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "024", cn_name: "運通銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "025", cn_name: "首都銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "039", cn_name: "荷蘭銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "040", cn_name: "中華開發", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "050", cn_name: "臺灣企銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "051", cn_name: "台北商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "052", cn_name: "新竹商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "053", cn_name: "台中商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "054", cn_name: "京城商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "056", cn_name: "花蓮企銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "057", cn_name: "台東企銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "075", cn_name: "東亞銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "081", cn_name: "匯豐銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "083", cn_name: "渣打銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "087", cn_name: "標旗銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "101", cn_name: "台北一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "102", cn_name: "華泰銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "103", cn_name: "臺灣新光商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "104", cn_name: "台北五信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "106", cn_name: "台北九信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "108", cn_name: "陽信銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "114", cn_name: "基隆一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "115", cn_name: "基隆二信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "118", cn_name: "板信銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "119", cn_name: "淡水一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "120", cn_name: "淡水信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "124", cn_name: "宜蘭信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "127", cn_name: "桃園信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "130", cn_name: "新竹一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "132", cn_name: "新竹三信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "139", cn_name: "竹南信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "146", cn_name: "台中二信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "147", cn_name: "三信銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "151", cn_name: "第七商銀", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "158", cn_name: "彰化一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "161", cn_name: "彰化五信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "162", cn_name: "彰化六信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "163", cn_name: "彰化十信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "165", cn_name: "鹿港信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "178", cn_name: "嘉義三信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "179", cn_name: "嘉義四信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "188", cn_name: "台南三信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "203", cn_name: "高雄二信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "204", cn_name: "高雄三信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "215", cn_name: "花蓮一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "216", cn_name: "花蓮二信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "222", cn_name: "澎湖一信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "223", cn_name: "澎湖二信", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "224", cn_name: "金門信合社", en_name: "", link: undefined, tag: BankType.Credit_Union },
   { code: "512", cn_name: "雲林漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "515", cn_name: "嘉義漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "517", cn_name: "南市區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "518", cn_name: "南縣漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "彌陀漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "永安漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "興達港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "521", cn_name: "林園區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "東港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "琉球區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "523", cn_name: "林邊區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "524", cn_name: "新港漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "525", cn_name: "澎湖區漁會", en_name: "", link: undefined, tag: BankType.Fisherperson },
   { code: "605", cn_name: "高雄市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "613", cn_name: "名間農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "永靖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "秀水農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "二林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "埔心農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "員林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "埤頭鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "614", cn_name: "竹塘農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "四湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "大埤農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "二崙農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "口湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "莿桐農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "褒忠農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "斗六農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "西螺農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "虎尾農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "崙背鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "台西農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "古坑農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "616", cn_name: "斗南農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "六腳農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "朴子農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "太保農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "鹿草農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "大埔農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "水上鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "民雄農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "溪口農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "竹崎農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "布袋鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "東石農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "新港農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "大林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "梅山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "嘉義農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "番路農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "617", cn_name: "義竹農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "歸仁農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "六甲農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "善化鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "西港農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "北門農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "佳里鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "永康農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "鹽水農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "新營農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "將軍農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "618", cn_name: "玉井農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "鳳山市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "阿蓮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "仁武農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "大社農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "田寮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "鳥松農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "梓官農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "林園農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "大寮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "橋頭農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "燕巢農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "永安農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "湖內農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "路竹農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "彌陀農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "甲仙農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "杉林農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "旗山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "岡山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "茄萣農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "619", cn_name: "美濃農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "恒春農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "滿州農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "新埤農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "枋山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "東港鎮農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "里港鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "南州農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "崁頂鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "麟洛農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "琉球農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "620", cn_name: "九如鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "富里鄉農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "壽豐農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "吉安農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "621", cn_name: "新秀農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "太麻里農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "東河農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "台東農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "成功農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "關山農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "池上農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "鹿野農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "622", cn_name: "長濱農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "624", cn_name: "澎湖農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "625", cn_name: "台中市農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "627", cn_name: "連江縣農會", en_name: "", link: undefined, tag: BankType.Farmers },
   { code: "700", cn_name: "中華郵政", en_name: "", link: undefined, tag: BankType.Post },
   { code: "803", cn_name: "聯邦銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "804", cn_name: "中華銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "805", cn_name: "遠東銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "806", cn_name: "復華銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "807", cn_name: "建華銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "808", cn_name: "玉山銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "809", cn_name: "萬泰銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "810", cn_name: "寶華銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "812", cn_name: "台新銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "814", cn_name: "大眾銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "815", cn_name: "日盛銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "816", cn_name: "安泰銀行", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "822", cn_name: "中國信託", en_name: "", link: undefined, tag: BankType.Bank },
   { code: "825", cn_name: "慶豐銀行", en_name: "", link: undefined, tag: BankType.Bank },
];
